var timing = window.performance.timing;
var redirectTime = timing.redirectEnd - timing.redirectStart;
console.log('重定向耗时',redirectTime);
var unloadTime = timing.unloadEventEnd - timing.unloadEventStart;
console.log('卸载上一个页面耗时',unloadTime);
var domainTime = timing.domainLookupEnd - timing.domainLookupStart;
console.log('DNS查询耗时',domainTime);
var tcpConnectTime = timing.connectEnd - timing.connectStart;
console.log('TCP连接耗时',tcpConnectTime);
var beforeDomLoadTime = timing.responseEnd - timing.navigationStart;
console.log('DOM开始加载前所花费时间',beforeDomLoadTime);
var responseTime = timing.responseEnd - timing.requestStart;
console.log('请求耗时',responseTime);
var domLoadTime = timing.domComplete - timing.domLoading;
console.log('DOM完成加载耗时',domLoadTime);
var domComplieTime = timing.domInteractive - timing.domLoading ;
console.log('DOM结构完成解析耗时',domComplieTime);
var contentLoadTime = timing.domContentLoadedEventEnd - timing.domContentLoadedEventStart;
console.log('脚本加载时间',contentLoadTime);
var loadTime = timing.loadEventEnd - timing.loadEventStart;
console.log('onload事件时间',loadTime);
var fullTime = redirectTime + unloadTime + domainTime + tcpConnectTime + responseTime + domLoadTime + domComplieTime ;
console.log('页面完全加载耗时',fullTime);